# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ; drop table user;
email: markus.scharitzer@mailbox.org
description: > # this means to ignore newlines until "baseurl:"
  Security. Student. 8CB2 3C56 1BD4 74E5 FB91 8EF8 8B6F 9890 10F7 0975
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://droptableuser.github.io" # the base hostname & protocol for your site, e.g. http://example.com
signoff: "markus"
share: false
links: 
  - name: Home
    url: /
    external: false
  - name: About me
    url: /about
    external: false

permalink: /posts/:title
defaults:
  - values:
      layout: "default"
#twitter_username: droptableuser
#github:  droptableuser
#author: 'Markus'
# Build settings
#markdown: redcarpet
#highlighter: pygments
#permalink: pretty
#paginate: 5
#theme: jekyll-theme-hacker
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
